"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "projeto plin",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      {/* <div>
        layout primeira pagina para colocar chave api
      </div> */}
      <body className={inter.className} style={{backgroundColor:"black"}}>{children}</body>
    </html>
  );
}
